// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADyeFCRCpunSQV-1FsaDwc8YkC1XI1EsQ',
    appId: '1:1016859547397:web:4aa1ac66ce7070229bc96c',
    messagingSenderId: '1016859547397',
    projectId: 'ai-fitness-journal',
    authDomain: 'ai-fitness-journal.firebaseapp.com',
    storageBucket: 'ai-fitness-journal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgqJZWMeE11jelwhmQdFx9Kl0i7rYK_Ik',
    appId: '1:1016859547397:android:12f8ffd6f83b7df39bc96c',
    messagingSenderId: '1016859547397',
    projectId: 'ai-fitness-journal',
    storageBucket: 'ai-fitness-journal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlatvg5Il22ewRbjpm4SCYnFa16NQ-ak',
    appId: '1:1016859547397:ios:26cc0050d7c8ded99bc96c',
    messagingSenderId: '1016859547397',
    projectId: 'ai-fitness-journal',
    storageBucket: 'ai-fitness-journal.firebasestorage.app',
    iosBundleId: 'com.example.caloriesTrackerFlutterApp',
  );
}
